  services:
    postgres:
      image: postgres:15
      container_name: ${APP_NAME}_pgsql
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: ${PGSQL_POSTGRES_PASSWORD}
        POSTGRES_USER: ${PGSQL_POSTGRES_USER}
        POSTGRES_DB: ${PGSQL_POSTGRES_DB}
      ports:
        - ${PGSQL_PORT}:5432

      volumes:
        - ${PGSQL_DIR}:/var/lib/postgresql/data
        - ${PGSQL_INIT}:/docker-entrypoint-initdb.d

      # networks:
      #   - app-network

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   container_name: go_backend  
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: admin
  #     DB_PASSWORD: secret
  #     DB_NAME: mydb
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - app-network
  #   volumes:
  #     - ../backend:/app
  #   restart: unless-stopped


# networks:
#   app-network:
#     driver: bridge

